import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { randomUUID } from "node:crypto"

export type ProjectTaskStatus = "pending" | "in_progress" | "done" | "blocked"

export type ProjectOpenTask = {
  id: string
  title: string
  priority: "P0" | "P1" | "P2"
  status: ProjectTaskStatus
}

export type ProjectDecision = {
  id: string
  summary: string
  at: string
}

export type ProjectState = {
  version: 1
  currentGoal: string
  projectMode: "greenfield" | "continue"
  openTasks: ProjectOpenTask[]
  decisions: ProjectDecision[]
  openQuestions: string[]
  lastSessionId?: string
  lastVerifiedAt?: string | null
  updatedAt: string
}

export function projectArisDir(workspacePath: string) {
  return join(workspacePath, ".aris")
}

export function projectStatePath(workspacePath: string) {
  return join(projectArisDir(workspacePath), "state.json")
}

export function projectStateMarkdownPath(workspacePath: string) {
  return join(projectArisDir(workspacePath), "STATE.md")
}

export function emptyProjectState(
  projectMode: "greenfield" | "continue" = "continue",
): ProjectState {
  return {
    version: 1,
    currentGoal: "",
    projectMode,
    openTasks: [],
    decisions: [],
    openQuestions: [],
    lastVerifiedAt: null,
    updatedAt: new Date().toISOString(),
  }
}

export async function readProjectState(
  workspacePath: string,
): Promise<ProjectState | null> {
  try {
    const raw = await readFile(projectStatePath(workspacePath), "utf8")
    return JSON.parse(raw) as ProjectState
  } catch {
    return null
  }
}

export async function ensureProjectState(
  workspacePath: string,
  projectMode: "greenfield" | "continue" = "continue",
): Promise<ProjectState> {
  const existing = await readProjectState(workspacePath)
  if (existing) return existing
  const state = emptyProjectState(projectMode)
  await writeProjectState(workspacePath, state)
  return state
}

export async function writeProjectState(
  workspacePath: string,
  state: ProjectState,
) {
  await mkdir(projectArisDir(workspacePath), { recursive: true })
  const next = { ...state, version: 1 as const, updatedAt: new Date().toISOString() }
  await writeFile(projectStatePath(workspacePath), JSON.stringify(next, null, 2), "utf8")
  await writeFile(projectStateMarkdownPath(workspacePath), renderStateMarkdown(next), "utf8")
  return next
}

export async function patchProjectState(
  workspacePath: string,
  patch: Partial<
    Pick<
      ProjectState,
      | "currentGoal"
      | "openTasks"
      | "decisions"
      | "openQuestions"
      | "lastSessionId"
      | "lastVerifiedAt"
      | "projectMode"
    >
  >,
): Promise<ProjectState> {
  const current = (await readProjectState(workspacePath)) ?? emptyProjectState(patch.projectMode)
  return writeProjectState(workspacePath, { ...current, ...patch })
}

/**
 * After a chat turn: keep goal fresh, stamp session, append decision if provided.
 */
export async function recordSessionHandoff(input: {
  workspacePath: string
  sessionId: string
  projectMode?: "greenfield" | "continue"
  goalFromUser?: string
  assistantSummary?: string
}): Promise<ProjectState> {
  const current =
    (await readProjectState(input.workspacePath)) ??
    emptyProjectState(input.projectMode ?? "continue")

  const decisions = [...current.decisions]
  if (input.assistantSummary?.trim()) {
    decisions.push({
      id: randomUUID(),
      summary: input.assistantSummary.trim().slice(0, 280),
      at: new Date().toISOString(),
    })
  }

  return writeProjectState(input.workspacePath, {
    ...current,
    projectMode: input.projectMode ?? current.projectMode,
    currentGoal: input.goalFromUser?.trim() || current.currentGoal,
    lastSessionId: input.sessionId,
    decisions: decisions.slice(-40),
  })
}

export function renderStateMarkdown(state: ProjectState): string {
  const tasks =
    state.openTasks.length === 0
      ? "- (none)"
      : state.openTasks
          .map((t) => `- [${t.status}] (${t.priority}) ${t.title}`)
          .join("\n")

  const decisions =
    state.decisions.length === 0
      ? "- (none yet)"
      : state.decisions
          .slice(-8)
          .map((d) => `- ${d.summary}`)
          .join("\n")

  const questions =
    state.openQuestions.length === 0
      ? "- (none)"
      : state.openQuestions.map((q) => `- ${q}`).join("\n")

  return `# Project state

> Auto-generated by Aris. Read this before continuing work.
> Updated: ${state.updatedAt}

## Current goal

${state.currentGoal || "(not set — set on next prompt)"}

## Mode

\`${state.projectMode}\`

## Open tasks

${tasks}

## Recent decisions

${decisions}

## Open questions

${questions}

## Last session

\`${state.lastSessionId ?? "none"}\`
`
}

/** Bundle loaded into the agent prompt before every continue turn. */
export async function loadProjectContinuityContext(workspacePath: string): Promise<{
  state: ProjectState | null
  stateMarkdown: string
  promptBlock: string
}> {
  const state = await readProjectState(workspacePath)
  let stateMarkdown = ""
  try {
    stateMarkdown = await readFile(projectStateMarkdownPath(workspacePath), "utf8")
  } catch {
    stateMarkdown = state ? renderStateMarkdown(state) : ""
  }

  if (!state && !stateMarkdown) {
    return { state: null, stateMarkdown: "", promptBlock: "" }
  }

  const promptBlock = [
    "## Project continuity (read before acting)",
    "Software never finishes — enhance this project; do not restart unless asked.",
    stateMarkdown || (state ? renderStateMarkdown(state) : ""),
  ].join("\n\n")

  return { state, stateMarkdown, promptBlock }
}
